apiVersion: v1
kind: Service
metadata:
  name: afnan-service
  namespace: default
  annotations:
   metallb.universe.tf/address-pool: address-pool
spec:
  type: LoadBalancer
  selector:
    vm.kubevirt.io/name: vm-afnan-image
  ports:
  - port: 443
    name: https
    targetPort: 443
    protocol: TCP
  - port: 5617
    name: ssh
    targetPort: 22
    protocol: TCP
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  - port: 9100
    name: node-exporter
    targetPort: 9100
    protocol: TCP
